#ifndef COMMON_EVENT_TYPE_HPP
#define COMMON_EVENT_TYPE_HPP

enum class EventType {
    CURSOR_POSITION_CHANGED,
    KEY_PRESSED,
    SCREEN_TOUCHED,
    SURFACE_CHANGED
};

#endif // COMMON_EVENT_TYPE_HPP
