// Copyright (c) 2022 Simon Puente
#ifndef APP_SRC_MAIN_CPP_COMMON_PROJECTION_HPP_
#define APP_SRC_MAIN_CPP_COMMON_PROJECTION_HPP_

enum class Projection { PERSPECTIVE, ORTHOGRAPHIC };

#endif // APP_SRC_MAIN_CPP_COMMON_PROJECTION_HPP_
