#ifndef APP_SRC_MAIN_CPP_EVENTBUS_EVENTTYPE_HPP_
#define APP_SRC_MAIN_CPP_EVENTBUS_EVENTTYPE_HPP_

enum class EventType {
  CURSOR_POSITION_CHANGED,
  KEY_PRESSED,
  SCREEN_TOUCHED,
  SURFACE_CHANGED
};

#endif // APP_SRC_MAIN_CPP_EVENTBUS_EVENTTYPE_HPP_
