#ifndef APP_SRC_MAIN_CPP_SHARED_EVENTS_KEY_HPP_
#define APP_SRC_MAIN_CPP_SHARED_EVENTS_KEY_HPP_

enum class Key { UNKNOWN, A_KEY, S_KEY, D_KEY, W_KEY, L_KEY, ESCAPE_KEY };

enum class PressState { UNKNOWN, KEY_PRESSED, KEY_HOLDED, KEY_RELEASED };

#endif // APP_SRC_MAIN_CPP_SHARED_EVENTS_KEY_HPP_
